# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4360026b4722dc0c8fbc536f91da1c27cb20d5f91ab3b82825db0fb7d32f7337764817a5a5c9eb80dbd38eb6f278a6d9431e6f7c85fec810a2d2c808625af961

test:
  secret_key_base: 6d60099c8b66325751533fefbc07c1e31623c0c0513688f0e300f9f3744d83d33eb0d7a3babced9bcd32d2bafbe9fcecfa8f5c0e4cc5a6afbe3edbd90dfbd6bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
